import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../src/components/Header';
import NewSessionForm from '../src/components/session/NewSessionForm';

const NewSession: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Router App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <NewSessionForm
        categories={[]}
        selectedCategoryIds={[]}
        requestCategories={() => {}}
        saveSession={() => {}}
        setSelectedCategoryIds={() => {}}
      />
    </div>
  )
}

export default NewSession;
